### ISSUE TITLE
Hey I Am Getting This Error If I Am Trying To Connect To MongoDb   Error: [DATABASE_NOT_READY] Use db.connect()     at Database.__readyCheck (/home/runner/Artic-Bot/node_modules/quickmongo/dist/index.js:570:13)     at Database.<anonymous> (/home/runner/Artic-Bot/node_modules/quickmongo/dist/index.js:182:12)     at Generator.next (<anonymous>)     at /home/runner/Artic-Bot/node_modules/quickmongo/dist/index.js:59:61

### ISSUE THREAD

**Issue by lovepytho** [Snowflake107/quickmongo#59]
const { Database } = require(`quickmongo`);
const config = require(`../config.js`);
const { connect } = require(`mongoose`);

connect(config.mongoURL,{useNewUrlParser : true , autoIndex : false}).then(() => console.log(`MONGO DB CONNECTED`))

const db = new Database(config.mongoURL)
db.connect();

module.exports = db;

**Comment by Zelak312** [comment]
Hey, from the error, it just says the database connection is not ready. This could happen if you don't await the connect method.

I am also curious on why you connect mongoose and quickmongo as well

**Comment by lovepytho** [comment]
bro but my database is ready and this error is world wide

**Comment by Zelak312** [comment]
Bro, first of, quickmongo is not really maintained anymore. If you still plan to use it. You should know that. I don't think it will receive updates. Quickmongo was given to us on 10/02/2022 from the developer. There was no update since which if you look on npm the last update was from 7 months ago. Since then I have not seen anyone with the same error as you that it is on the github issue or the quickmongo support channel in the plexidev discord server. I have had many that had  problems unrelated to the connection. Which means you are the first one to have this problem in 7 months. Just from these statistics, I highly doubt it's a problem with quickmongo itself. As I stated in my first comment. You should use await on the db.connect method. I was not talking about your mongo database not being ready. I was saying that the connection to the mongo database was not ready because you (in the code you provided) doesn't seem to await the db.connect method which can definitely cause the issue. The db.connect method should be awaited. That is very likely the problem you have. So please try to await the db.connect method and test if it resolves it. Otherwise, I will test it myself to see if that is in fact a quickmongo problem.
