### ISSUE TITLE
CONCERN: Security of this package

### ISSUE THREAD

**Issue by BowkC** [Snowflake107/quickmongo#61]
Currently, the schema model used doesn't appear to be encrypted.
I would love to see encryption implemented by the use of the [mongoose-encryption](https://github.com/joegoldbeck/mongoose-encryption) package which directly plugs into the schema. This would greatly improve the security of the package. It'd be much appreciated, it's a shame this package is rarely updated/maintained. Someone should create and maintain a fork really.

**Comment by BowkC** [comment]
I mean just looking at the dependency graph & package.json there are also some unnecessary and unused dependencies. 
Like how quick.db is listed as a dependency, despite this package certainly not using it (excluding there being a few commented-out lines which contain quick.db code). It might also be wise to refine that.

**Comment by Zelak312** [comment]
Hey, yes this is raraly updated/maintaned since it probably won't be anymore.
This packages was given to plexidev by it's maintainer. Unfortunately nobody in plexidev took this package up. This package will probably be archived if you want my honest opinion.
Why? Because no one is working on it or plan to and because now quick.db which was the source of this package starting since quick.db was only using sqlite is now also able to use mongo. So there is really no point in this package anymore. Cheers!

Also the quick.db listed as a dependency is because quickmongo provided a mongo driver for quick.db!
